######################################################################
# Automatically generated by qmake (2.01a) ?? 10? 23 10:55:25 2016
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

QT += widgets 

unix:MOC_DIR=.tmp
unix:UI_DIR=.tmp
unix:OBJECTS_DIR=.tmp

# Input
HEADERS += mainwidget.h \
		   person.h \

SOURCES += main.cpp \
		   person.cpp \
		   mainwidget.cpp \


